export const USER_EVENTS = {
    USER_CREATED : 'USER_CREATED',
    USER_UPDATED : 'USER_UPDATED',
    USER_DELETED : 'USER_DELETED'
}

export const BLOG_EVENTS = {
    BLOG_CREATED : 'BLOG_CREATED',
    BLOG_UPDATED : 'BLOG_UPDATED',
    BLOG_DELETED : 'BLOG_DELETED'
}